// Certificates & Achievements
export const CERTS = [
  {
    id: 'cert-1',
    title: 'Graphic Designing — Professional Training',
    issuer: 'KPITB (Merged Area Digital Connect Program)',
    duration: '3 Months Intensive',
    year: '2025',
    category: 'tech',
    categoryLabel: 'Tech & Design',
    image: 'graphic-designing.jpg',
    description: 'Comprehensive design training certified by Khyber Pakhtunkhwa Information Technology Board (KPITB), focusing on digital visual design and layout systems.',
  },
  {
    id: 'cert-2',
    title: 'Youth Community Leadership & Peacebuilding',
    issuer: 'Resilient Young Waziristan (RYW)',
    duration: '3-Day Ambassador Boot Camp',
    year: '2024',
    category: 'leadership',
    categoryLabel: 'Leadership & Community',
    image: 'youth-leadership.jpg',
    description: 'Selected as Youth Peace Ambassador representing youth advocacy, team collaboration, and community peacebuilding initiatives.',
  },
  {
    id: 'cert-3',
    title: 'Best Player — Football Championship',
    issuer: 'Govt. Degree College No. 1, D.I. Khan',
    duration: 'Intramural Tournament',
    year: '2025',
    category: 'sports',
    categoryLabel: 'Athletics & Sports',
    image: 'football-college.jpg',
    description: 'Awarded Best Football Player of the Tournament in college intramural sports competitions for team leadership and athletic performance.',
  },
  {
    id: 'cert-4',
    title: 'Player of the Tournament — Football',
    issuer: 'Ummah Children Academy, Nowshera',
    duration: 'Annual Sports Gala',
    year: '2024',
    category: 'sports',
    categoryLabel: 'Athletics & Sports',
    image: 'football-academy.jpg',
    description: 'Recognized as Best Player of the Tournament demonstrating dedication, tactical discipline, and exceptional teamwork.',
  },
  {
    id: 'cert-5',
    title: 'Best All-Rounder — Cricket Tournament',
    issuer: 'Punjab Group of Colleges (Meraj Campus, D.I. Khan)',
    duration: 'College Cricket Series',
    year: '2023',
    category: 'sports',
    categoryLabel: 'Athletics & Sports',
    image: 'cricket-allrounder.jpg',
    description: 'Awarded Best All-Rounder trophy for balanced excellence across batting and bowling in inter-campus cricket championships.',
  },
]
